#!/bin/bash

docker rm registry
docker run -ti --name registry -p 5000:5000 -v /Users/peterbryzgalov/work/docker-registry:/docker-registry \
    -v /Users/peterbryzgalov/work/docker-registry-driver-git:/docker-registry-driver-git \
    registry /bin/bash
    
