#!/bin/bash

if [ ! -d gitdriver ]
then
    mkdir gitdriver
    cp -r ../docker-registry-driver-git/ ./gitdriver/
fi
docker rm reg
docker rmi reg
docker build -t reg .
docker run -ti --name reg reg /bin/bash
